apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
resources:
  - namespace.yaml
  - config.yaml
  - storage.yaml
  - postgres.yaml
  - redis.yaml
  - app.yaml
  - fcm-worker.yaml
  - network-policy.yaml
